ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.8
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  #  profile: D:/ruoyi/uploadPath
  profile: C:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://172.25.249.17:3306/ruoyi_fast?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 172.25.249.17
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
#  rabbitmq:
#    port: 5672
#    host: 172.25.249.17
#    username: guest
#    password: guest

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

## MyBatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.ruoyi.project.**.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mybatis/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml

mybatis-plus:
  # 配置别名扫描的包
  #  typeAliasesPackage: com.ruoyi.project.**.domain
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper.xml的位置
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 配置全局配置文件的路径
  global-config:
    # 配置主键策略，自动生成主键
    db-config:
      id-type: none
      # 配置逻辑删除的字段
      logic-delete-field: is_deleted
      # 配置逻辑删除的字段值
      logic-delete-value: 1
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  #  pathMapping: /dev-api
  #  pathMapping: /


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者
  author: ruoyi
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.ruoyi.project.system
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_,t_

#阿里云相关配置(Access要在系统变量中设置)
aliyun:
  accessparams:
    KeyId: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    KeySecret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
  smsparams:
    UserPrincipalName: zgcbuild@1160848283821582.onaliyun.com 
    Password: q85238737
    SignName: 个人博客张广成
    TemplateCode: SMS_470400116
    Endpoint: dysmsapi.aliyuncs.com
    RegionId: cn-qingdao
  ocrparams:
    Endpoint: ocr-api.cn-hangzhou.aliyuncs.com
    RegionId: cn-hangzhou
    
#支付宝支付相关配置
alipay:
  payparams:
    AppId: ${ALIBABA_CLOUD_PAY_APP_ID}  
    MerchantPrivateKey: ${ALIBABA_CLOUD_PAY_MERCHANT_PRIVATE_KEY} 
    AlipayPublicKey: ${ALIBABA_CLOUD_PAY_ALIPAY_PUBLIC_KEY} 
    GatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do #沙箱环境
    NotifyUrl: https://www.zgcbuild.top/  #异步通知地址
    ReturnUrl: https://www.zgcbuild.top/pay/alipay/pc/return  #回调地址
    SignType: RSA2  #签名类型
    Charset: utf-8  #字符编码
    Format: json  #返回格式
    Version: 1.0  #版本号
    ProductCode: FAST_INSTANT_TRADE_PAY #产品码 根据使用不同的支付场景更换产品码

#微信支付相关配置
wxpay:
  payparams:
#    MerchantId: 1606444287
#    AppId: wxff0cf54e2af1fa40
#    PrivateKeyPath: cert_wxpay/apiclient_key.pem
#    MerchantSerialNumber: 3581E71E4D77A1EE57D50E8FEB20F3B977C3C386
#    ApiV3Key: lqozpTpcLhz4NiMfL2o99zFdsI5IkEDv
#    NotifyUrl: https://www.zgcbuild.top/api/pay/wx/wxnotify
#    ReturnUrl: https://www.zgcbuild.top/api/pay/wx/wxreturn
    MerchantId: 1638660091  # 商户号
    AppId: wxc7fa0677f0875535   #AppId
    PrivateKeyPath: wx/apiclient_key.pem  
    PublicCertPath: wx/apiclient_cert.pem
    MerchantSerialNumber: 52DB932DAE765A3705DC5287EB438A080F0B67B6  #平台序列号
    ApiV3Key: e3a7f079c2237df57f9923e5258d5172      #v3密钥
    NotifyUrl: https://www.zgcbuild.top/api/pay/wx/wxnotify
    ReturnUrl: https://www.zgcbuild.top/api/pay/wx/wxreturn

#对象存储相关配置
dromara:
  x-file-storage: #文件存储配置
    default-platform: aliyun-oss-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        accessKey: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
        secretKey: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
        end-point: oss-cn-hangzhou.aliyuncs.com
        bucket-name: zgcbuild
        domain: https://zgcbuild.oss-cn-hangzhou.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path:  zgcbuild/ # 基础路径
  

